name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and test
        run: |
          npm install --legacy-peer-deps
          npm run lint
          npm run test

      - name: Build
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
          NEXT_PUBLIC_API_ENDPOINT: ${{ vars.NEXT_PUBLIC_API_ENDPOINT }}
          NEXT_PUBLIC_DEFAULT_RECIPE_YIELD: ${{ vars.NEXT_PUBLIC_DEFAULT_RECIPE_YIELD }}
          NEXT_PUBLIC_DEFAULT_RECIPE_YIELD_NAME: ${{ vars.NEXT_PUBLIC_DEFAULT_RECIPE_YIELD_NAME }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          CATEGORY_IF_NON_EXIST: ${{ vars.CATEGORY_IF_NON_EXIST }}
          COOKIE_SECURE_PREFIX: ${{ vars.COOKIE_SECURE_PREFIX }}
          OPENAI_API_KEY: ${{ vars.OPENAI_API_KEY }}
        run: npm run build

      - name: Deploy
        env:
          DOMAIN: mat.stenberg.io
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.APP_SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $DOMAIN >> ~/.ssh/known_hosts
          rsync -azHd ./.next ./package.json ./node_modules jonas@$DOMAIN:/usr/local/bin/mat.stenberg.io/
          ssh -o StrictHostKeyChecking=no jonas@$DOMAIN 'systemctl restart mat.service'
